// <auto-generated />
using Ef_Vehiclemanagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework_CRUD_VMS.Migrations
{
    [DbContext(typeof(VehicleContext))]
    partial class VehicleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ef_Vehiclemanagement.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Owner_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vehicle_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vehicle_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vehicle_Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Vehicle_Id");

                    b.ToTable("Vehicledetails");
                });
#pragma warning restore 612, 618
        }
    }
}
